### ISSUE TITLE
Minor readme issue

### ISSUE THREAD

**Issue by EddyJLSH** [mangata-finance/mangata-node#102]
The readme has a typo for the docker instructions to run a node. 

`./scripts/build-manga-node-docker-image.sh` misspells `mangata`, it should be `./scripts/build-mangata-node-docker-image.sh`.

**Comment by goncer** [comment]
@EddyJLSH plz update it and create a PR :)

**Comment by gleb-urvanov** [comment]
Resolved https://github.com/mangata-finance/mangata-node/pull/110
