### ISSUE TITLE
Mangata Chainspec complete with bootnodes

### ISSUE THREAD

**Issue by sourabhniyogi** [mangata-finance/mangata-node#300]
Can you post your kusama chainspec -- including bootnodes?  We [Polkaholic.io] are building a block explorer cf 
 https://mangatax.polkaholic.io/chain/mangatax
and are attempting to run a full archive node (to index Mangata blocks, xcm transfers into and out of Mangata, etc.) and couldn't find this in your repo.    

Thank you!

**Comment by iStrike7** [comment]
https://github.com/mangata-finance/chainspec
