### ISSUE TITLE
Strange execution order for sudo.Sudid and xyk.LiquidityActivated

### ISSUE THREAD

**Issue by tmcgroul** [mangata-finance/mangata-node#452]
Hi i am trying to index mangata-x network and noticed unexpected (maybe it's just for me) behaviour.

Block where i found it - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmangata-x.api.onfinality.io%2Fpublic-ws#/explorer/query/0x343fb7105afe232c7a2296028baee4ab2bb73e65d310f93039b59decd35ca8f8
In the block we can see that `xyk.LiquidityActivated` event was emitted during `sudo.sudo` extrinsic while `sudo.Sudid` was emitted during `xyk.activateLiquidity`. And my expectation that the events had to be emitted within the calls from their pallets.

I am wondering if it's a common behaviour for substrate or this is an accident and should be handled in a unique way?

**Comment by mateuszaaa** [comment]
its not common for substrate, it is specific to our chain. At that time every TX was present in 2 consecutive blocks. First block is where tx was included and the following one is where it was executed. In mangata compering to any other substrate tx inclusion & execution does not happen in the same block. Txs included in block N are randomly shuffled and executed in the following(N+1) block (thats why you see events not aligned with txs). 

Recently we aligned our solution to keep txs<->events aligned in polkadot.js, but we cant apply it for historical data unfortunately

**Comment by majusko** [comment]
Closing as resolved
